### ISSUE TITLE
[self.view addSubview:self.commentView]; EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by canaksoy** [daltoniam/DCCommentView#1]
In UITableViewController, I cannot add.

self.commentView = [[DCCommentView alloc] initWithScrollView:self.tableView frame:self.view.bounds];
[self.view addSubview:self.commentView];

**Comment by daltoniam** [comment]
Yeah DCCommentView won't with a UITableViewController. The way it works with attaching to the superview of the scrollView/tableView which the tableView in UITableViewController doesn't really have a superview it can attach to. 

You can get it working by switching over to a UIViewController and adding a UITableView to it then following the code above it should work properly. Any questions let me know
erly. Any questions let me know.
